Update pipeline test-fastlane-build

diff --git a/.harness/testfastlanebuild.yaml b/.harness/testfastlanebuild.yaml
--- a/.harness/testfastlanebuild.yaml
+++ b/.harness/testfastlanebuild.yaml
@@ -140,7 +140,6 @@ pipeline:
         - stage:
             name: Execute tests on Ubuntu
             identifier: Execute_tests_on_Ubuntu
-            description: ""
             type: CI
             spec:
               cloneCodebase: true
@@ -177,9 +176,9 @@ pipeline:
                         shell: Sh
                         command: |-
                           #!/bin/bash -eo pipefail
-                          gem install bundler -v 2.3.14
-                          bundle config set --local path .bundle
-                          bundle check 
+                          sudo gem install bundler -v 2.3.14
+                          sudo bundle config set --local path .bundle
+                          sudo bundle check 
                         envVariables:
                           LC_ALL: C.UTF-8
                           LANG: C.UTF-8
@@ -194,7 +193,7 @@ pipeline:
                         shell: Sh
                         command: |-
                           #!/bin/bash -eo pipefail
-                          bundle exec danger || echo "danger failed"
+                          sudo bundle exec danger || echo "danger failed"
                         envVariables:
                           LC_ALL: C.UTF-8
                           LANG: C.UTF-8
@@ -212,8 +211,8 @@ pipeline:
                         shell: Sh
                         command: |-
                           #!/bin/bash -eo pipefail
-                          gem install bundler:2.3.14
-                          bundle exec fastlane execute_tests
+                          sudo gem install bundler:2.3.14
+                          sudo bundle exec fastlane execute_tests
                         envVariables:
                           LC_ALL: C.UTF-8
                           LANG: C.UTF-8
